### ISSUE TITLE
Use maps for variable grouping

### ISSUE THREAD

**Issue by HugoGiraudel** [Cyber-Duck/hoisin.scss#11]
I feel like you could make a nice use of Sass maps for your configuration variables:

``` scss
$colors: (
  error: #FF0000 #FFE5E5,
  success: #339900 #EAF5E5,
  info: #3399FF #EAF5FF,
  warning: #FFFF00 #FFFFE5
);

$breakpoints: (
  large: 1024px,
  medium: 600px,
  small: 240px
);
```

**Comment by ramono** [comment]
I'm going to add configuration variables as maps as an option, and also add a few functions to handle variables in maps, but the basic variables will stay as they are for now. I don't see a real benefit on complicating the way the breakpoints are handled at the moment until I implement an easier way to use breakpoints like a `respond-to` mixin or similar.
